-- A1 B1 Karimen Reviewer shared ranking tables
-- Run this once in Supabase > SQL Editor > New query > Run.

create table if not exists public.live_exams (
  session_id text primary key,
  display_name text not null,
  avatar text not null default '🚙',
  bank text not null default 'All',
  set_label text not null default 'All',
  total_questions integer not null default 50,
  answered integer not null default 0,
  correct integer not null default 0,
  started_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  status text not null default 'active'
);

create table if not exists public.exam_results (
  id bigint generated by default as identity primary key,
  session_id text not null,
  display_name text not null,
  avatar text not null default '🚙',
  bank text not null default 'All',
  set_label text not null default 'All',
  score integer not null,
  total_questions integer not null,
  percent numeric(5,1) not null,
  elapsed_seconds numeric(10,1) not null,
  passed boolean not null default false,
  completed_at timestamptz not null default now()
);

create index if not exists live_exams_last_seen_idx on public.live_exams(last_seen desc);
create index if not exists exam_results_completed_idx on public.exam_results(completed_at desc);
create index if not exists exam_results_name_idx on public.exam_results(display_name);

-- The Streamlit server uses the Supabase secret key stored in Streamlit Secrets.
-- Keep RLS enabled and do not create public anonymous policies.
alter table public.live_exams enable row level security;
alter table public.exam_results enable row level security;
