create extension if not exists pgcrypto;

create table if not exists public.bible_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  xp integer not null default 0 check (xp >= 0),
  streak integer not null default 0 check (streak >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bible_questions (
  id uuid primary key default gen_random_uuid(), external_id text unique,
  question_type text not null, book text, chapter integer, verse_start integer, verse_end integer,
  difficulty smallint not null default 1 check (difficulty between 1 and 5),
  prompt text not null, choices jsonb, answer jsonb, explanation text, reference_text text,
  content_class text not null default 'fact' check (content_class in ('fact','context','interpretation','wisdom','open_question')),
  source_name text not null, source_version text, source_url text, license text, attribution text,
  reviewed boolean not null default false, created_at timestamptz not null default now()
);

create table if not exists public.bible_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id uuid references public.bible_questions(id) on delete set null,
  external_question_id text, correct boolean not null, response jsonb,
  xp_earned integer not null default 0, created_at timestamptz not null default now()
);

create table if not exists public.bible_mastery (
  user_id uuid not null references auth.users(id) on delete cascade,
  topic text not null, score numeric(5,2) not null default 0 check (score between 0 and 100),
  attempts integer not null default 0, correct integer not null default 0,
  next_review_at timestamptz, updated_at timestamptz not null default now(),
  primary key (user_id, topic)
);

create table if not exists public.bible_polls (
  id uuid primary key default gen_random_uuid(), prompt text not null, context text,
  options jsonb not null, scripture_refs jsonb, content_class text not null default 'open_question',
  active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.bible_poll_votes (
  poll_id uuid not null references public.bible_polls(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  option_index integer not null, created_at timestamptz not null default now(),
  primary key (poll_id, user_id)
);
create table if not exists public.bible_groups (
  id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null, created_at timestamptz not null default now()
);

alter table public.bible_profiles enable row level security;
alter table public.bible_questions enable row level security;
alter table public.bible_attempts enable row level security;
alter table public.bible_mastery enable row level security;
alter table public.bible_polls enable row level security;
alter table public.bible_poll_votes enable row level security;
alter table public.bible_groups enable row level security;

create policy "profiles read own" on public.bible_profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "profiles insert own" on public.bible_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "profiles update own" on public.bible_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "questions public read" on public.bible_questions for select to anon, authenticated using (reviewed = true);
create policy "attempts read own" on public.bible_attempts for select to authenticated using ((select auth.uid()) = user_id);
create policy "attempts insert own" on public.bible_attempts for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "mastery read own" on public.bible_mastery for select to authenticated using ((select auth.uid()) = user_id);
create policy "mastery insert own" on public.bible_mastery for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "mastery update own" on public.bible_mastery for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "polls public read" on public.bible_polls for select to anon, authenticated using (active = true);
create policy "votes read own" on public.bible_poll_votes for select to authenticated using ((select auth.uid()) = user_id);
create policy "votes insert own" on public.bible_poll_votes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "votes update own" on public.bible_poll_votes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "groups read own" on public.bible_groups for select to authenticated using ((select auth.uid()) = owner_id);
create policy "groups insert own" on public.bible_groups for insert to authenticated with check ((select auth.uid()) = owner_id);

revoke all on public.bible_profiles, public.bible_questions, public.bible_attempts, public.bible_mastery, public.bible_polls, public.bible_poll_votes, public.bible_groups from anon, authenticated;
grant select on public.bible_questions, public.bible_polls to anon, authenticated;
grant select, insert, update on public.bible_profiles, public.bible_attempts, public.bible_mastery, public.bible_poll_votes, public.bible_groups to authenticated;
