[theme]
base = "light"
primaryColor = "#2b8cff"
backgroundColor = "#edf6ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#20314d"
font = "sans serif"

[server]
headless = true
maxUploadSize = 20
